image: node:9.2.0

pages:
  cache:
    paths:
    - ./node_modules/
 
  stage: deploy
#   before_script:
#   - npm install

  script:
  - npm install

  artifacts:
    paths:
    - public # mandatory, other folder won't work
  only:
  - master # or dev, the branch you want to publish
